Now only single program is created with all cm sigs. Could not analyze whole rt.jar with -array option as it throws NoSuchMethodError. However the program works with other applications. Need to really optimize the way it analyze the methods - it is overhead!